export const FETCH_PRODUCT="FETCH_PRODUCT";
export const ORDER_PRODUCT_BY_PRICE="ORDER_PRODUCT_BY_PRICE";
export const ORDER_PRODUCT_BY_SIZE="ORDER_PRODUCT_BY_SIZE";
export const ADD_TO_CART="ADD_TO_CART";
export const REMOVE_TO_CART="REMOVE_TO_CART";